### ISSUE TITLE
Running Model On Windows

### ISSUE THREAD

**Issue by Ryan-nd** [obi-ml-public/ehr_deidentification#10]
Hi, I am trying to run and train the model on Windows, without the use of Linux, however under the requirement.txt requires Allennlp which is only available in Mac & Linux. Would like to ask if the model would still be able to run generally without the package as I would want to further fine-tune/train the model. Hope to hear from the team soon.

**Comment by prajwal967** [comment]
The allenlp package is used if you want to use CRF decoding. We don't actually use it, you can get the model/package to work without allenlp, but you might need to change the source code to remove the scripts that contain references to it.

The scripts in this folder use it: https://github.com/obi-ml-public/ehr_deidentification/tree/main/src/robust_deid/sequence_tagging/models/hf/crf

You can git clone the project, remove this folder and run fine-tuning without using allenlp. I believe this should work. Let us know if there are any issues.

**Comment by Ryan-nd** [comment]
Hi,
Thanks for the quick response! Appreciate it! Will try it out.
