### ISSUE TITLE
citing?

### ISSUE THREAD

**Issue by markskrass** [obi-ml-public/ehr_deidentification#2]
How should we cite this work?

**Comment by mxhm** [comment]
Hi, thanks for asking! We're still in the process of publishing the manuscript for this project, but I just generated a zenodo DOI for the software, in case that's useful:

[![DOI](https://zenodo.org/badge/458346577.svg)](https://zenodo.org/badge/latestdoi/458346577)

We'll also add citation info for the publication once we have it.
