### ISSUE TITLE
is the typing dependency needed

### ISSUE THREAD

**Issue by matthewchung74** [obi-ml-public/ehr_deidentification#4]
Do you still need this `typing~=3.10.0.0` in requirements.txt? 

per here https://pypi.org/project/typing/

```
NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT, because stdlib takes higher precedence than the installation directory. To get a newer version of the typing module in Python 3.5 or later, you have to upgrade to a newer Python (bugfix) version. For example, typing in Python 3.6.0 is missing the definition of ‘Type’ – upgrading to 3.6.2 will fix this.
```

and I see 3.7 is a dependency in the Conda file.

**Comment by prajwal967** [comment]
You're right, the typing dependency is not explicitly needed. We generated the requirements file and it must have got in there somehow.

**Comment by matthewchung74** [comment]
It ok if I send another MR for it?

**Comment by prajwal967** [comment]
Sorry, I missed this earlier. Yes, you can send a pull request, and we can merge it. Thanks!
