### ISSUE TITLE
How to infer using GPU?

### ISSUE THREAD

**Issue by omeruth** [obi-ml-public/ehr_deidentification#8]
Could you please tell at which part of the code we can check for gpus and if available use those for inference? Assume train and testing flags are false under config file. Thanks

**Comment by prajwal967** [comment]
This line begins running the forward pass: https://github.com/obi-ml-public/ehr_deidentification/blob/88751ab1f95d23d54ded39385adb8a27f57a6f72/src/robust_deid/sequence_tagging/sequence_tagger.py#L600 

The checking for GPU's is handled by the HuggingFace trainer object - we don't do anything explicitly. You will make sure your parameters in the config file are correct.

FOr inference you will need to set do_predict to True though
