### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by rosspalmermd** [obi-ml-public/ehr_deidentification#9]
Hi, I noticed that your demo is not working:

https://huggingface.co/spaces/obi/Medical-Note-Deidentification

**Comment by prajwal967** [comment]
We're looking into it, we'll post here when we have an update. Thank you for letting us know!

**Comment by rosspalmermd** [comment]
Great, thanks for your response! I'm really excited about what you're doing.

**Comment by omri374** [comment]
Thanks for the amazing work! This is one of the best models out there for clinical notes de-id, and we've integrated it into Microsoft Presidio. If you'd like to check it out until the official demo is up again, you can also try it out on the Presidio demo: https://huggingface.co/spaces/presidio/presidio_demo

**Comment by prajwal967** [comment]
It seems like we're running into a gradio issue. Specifically the one listed here: https://github.com/gradio-app/gradio/issues/4912. Hopefully they respond soon and we can fix it on our end.

As Omri mentioned, they've integrated the model into Microsoft Presidio. You can use their space for access to the model, their demo is neat and easy to use!

**Comment by rosspalmermd** [comment]
Presidio is incredible, exactly what I was looking for. Thanks Prajwal and
Omri for making my project happen.

**Comment by freddyaboulton** [comment]
PR to fix space here: https://huggingface.co/spaces/obi/Medical-Note-Deidentification/discussions/2

**Comment by prajwal967** [comment]
Thank you!
We had to make a few additional changes to fix the package conflicts, and the demo is back up and running!

**Comment by rosspalmermd** [comment]
Grateful to to you Prajwal.
